### ISSUE TITLE
debian

### ISSUE THREAD

**Issue by coachshea** [sr/cbk#1]
I am try to build this on debian jessie. When I run make, I get this following error:

/bin/sh: 1: fpm: not found
Makefile:49: recipe for target 'cbk_1.0.0_all.deb' failed
make: **\* [cbk_1.0.0_all.deb] Error 127

Any help is greatly apprecaited.

**Comment by sr** [comment]
@coachshea Building a debian package requires the [fpm](https://github.com/jordansissel/fpm) rubygem. Install it with:

```
gem install fpm
```
